In [1]:
# HOW TO USE NUMPY TO PICK OUT RANDOM NUMBERS

In [12]:
import numpy as nm

# Since numpy focuses on array of numbers, let us first generate an array of numbers of a
# particular size
r_array = nm.random.rand(2,5)

print(r_array)#This automatically prints a floating array using the parameters given

# Now to generate a random interger we use the random randint() function
r_interger = nm.random.randint(20)

print(r_interger)

# To generate a random float
r_float = nm.random.rand()# NB: No parameters were given
# This particular one prints floating numbers between 0 and 1
print(r_float)

# To generate an array of intergers using the randint
int_array = nm.random.randint(20, size=(4))

print(int_array)# This prints an array of intergers

# How to get a random number from an array. 
# Over here we use the random choice which enables us to pick randomly from an array
r_in_an_array = nm.random.choice([1,2,5,34])

print(r_in_an_array)

[[0.26357033 0.36215456 0.70983601 0.72904773 0.43733894]
 [0.6533933  0.60135764 0.98426646 0.99602703 0.28345374]]
1
0.08665343959306082
[ 2  7 19 19]
1


In [13]:
# The use of the enumerate function in NUMPY


In [20]:
# it shows you the size as in the position of each digit in the area regarding their rows and 
# columns
# This is a 2d array in which we are using the ndenumerate function
a = nm.array([[2,4], [6,1]])
for i, x in nm.ndenumerate(a):
    print(i,x)
    
#To enumerate a 1D array
arr = nm.array([1,2,3])
for index, x in nm.ndenumerate(arr):
    print(index, x)

(0, 0) 2
(0, 1) 4
(1, 0) 6
(1, 1) 1
(0,) 1
(1,) 2
(2,) 3
