# Boolean arrays: Fancy indexing and masking

In [2]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([True, True, False])
c = a[b]
print(c)
# It isn't going to pick 3 cause the False element tells it to ignore that particular value

[1 2]


In [3]:
# USING BOOLEAN TO FILTER AN ARRAY
a = np.arange(1, 10)
b =  a>5
print(b)

c= a[b]
print(c)
# It gives the true element to all values following the given parameter in B whileignoringtherest

[False False False False False  True  True  True  True]
[6 7 8 9]


In [5]:
# Using fancy indexing to select multiple elements
arr = np.array([1,2,3,4,5,6,7,8,9])
# To select elements at index 1,2,5,7
select_elements = arr[[2,5,7]]
print(select_elements)
# This picks out the elements at the specified index

[3 6 8]


In [9]:
# FANCY INDEXING FOR SORTING NUMPY ARRAY
arr1 = np.array([3,2,5,7,8,9,6,1])
# sorting array using fancy indexing
sorted_arr1 = arr1[np.argsort(arr1)]# It arranges the array from ascending to descending order
print(sorted_arr1)

sorted_arr1 = arr1[np.argsort(-arr1)]# It arranges the array from descending to ascending order
print(sorted_arr1)

[1 2 3 5 6 7 8 9]
[9 8 7 6 5 3 2 1]


In [10]:
# Using fancy indexing to assign specufic new values to specific elements
arr1 = np.array([3,2,5,7,8,9,6,1])
#Create a list of new indices to assign new values
indices = [1, 3, 6]
# Create a new array of values to assign
new_values = [10,6,9]
# NOW useing F.I to assign new values to specific elements
arr1[indices] = new_values

print(arr1)


[ 3 10  5  6  8  9  9  1]


MASKING: A masked array is the combo of a standard numpy.ndarray and a mask. A mask is either nomask, indicating that no value of the associated array is invalid, or an array of booleans that determines for each element of an associated array whether the value is valid or not. When an element of of the mask is false, the corresponding element of the associated array is valid and said to be unmasked. When an element of the mask is true, the corresponding element of that array is said to be masked(invalid).

In [13]:
import numpy.ma as ma
x = np.array([1,2,3,-6,8])
# Now it's glaring that the fourth element is invalid or seems inconsistent, now we use masking
mx = ma.masked_array(x, mask=[0,0,0,1,0])# 1 is known as false while 0=TRUE
# Now we can get the mean of those values while ignoring the inconsistent value or error
mx.mean()

3.5